apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
    version: v1
spec:
  selector:
    matchLabels:
      app: redis
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        version: v1
    spec:
      containers:
      - name: main
        image: redis:6.0