apiVersion: v1
kind: Service
metadata:
  name: space-cloud
  labels:
    app: space-cloud
spec:
  ports:
    - targetPort: 4122
      port: 4122
      name: http
  type:  LoadBalancer
  selector:
    app: space-cloud