apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: greeting-app
    version: latest
  name: greeting-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greeting-app-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 6
