apiVersion: v1
kind: Service
...
---
apiVersion: extensions/v1beta1
kind: Deployment
...
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
...







apiVersion: v1
kind: Application
spec:
  helm: app-a:v1
...
---
apiVersion: v1
kind: Application
spec:
  helm: app-b:v1
...







